version: '3.8'
services:
  backend:
    build: ./backend
    environment:
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_PORT=${DATABASE_PORT}
    - JWT_SECRET=${{ secrets.JWT_SECRET }}
    - JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
    - GMAIL_HOST=${{ secrets.GMAIL_HOST }}
    - GMAIL_USER=${{ secrets.GMAIL_USER }}
    - GMAIL_PASS=${{ secrets.GMAIL_PASS }}
    image: "vinetage/backend:0.1"
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    image: "vinetage/frontend:0.1"
    ports:
      - "5173:5173"
    depends_on:
      - backend
