version: '3.8'
services:
  backend:
    build: ./backend
    image: "vinetage/backend:0.1"
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    image: "vinetage/frontend:0.1"
    ports:
      - "5173:5173"
    depends_on:
      - backend
