name: Build and Test Docker Compose

on:
  push:
    branches:
      - release  # branch for the release (Runs when the code is merged into release)

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest  # Ubuntu for now can change to different one

#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v2

#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v2

#       - name: Set up Docker Compose
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y docker-compose

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}  # Add your Docker Hub username to GitHub Secrets
#           password: ${{ secrets.DOCKERHUB_TOKEN }}  # Add your Docker Hub token to GitHub Secrets

#       - name: Build and run Docker Compose
#         run: |
#           docker-compose -f docker-compose.yml up -d --build
#           docker-compose logs

#       - name: Push Docker images to Docker Hub
#         run: |
#           docker-compose -f docker-compose.yml push
          
#       - name: Shut down Docker Compose
#         run: |
#           docker-compose down
